web/router.ex
defmodule Potion.Router do
  use Potion.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Potion.CurrentUserPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Potion do
    pipe_through :browser # Use the default browser stack

    # home
    get "/", PageController, :index

    # resources
    resources "/users", UserController do
      resources "/posts", PostController
    end

    resources "/posts", PostController, only: [] do
      resources "/comments", CommentController, only: [:create, :delete, :update]
    end

    resources "/login", SessionController, only: [:index, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Potion do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Potion.LayoutView do
  use Potion.Web, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

web/templates/layout/alerts.html.eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= if current_user = @conn.assigns[:current_user] do %>
      <%= tag :meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", current_user.id) %>
    <% end %>

    <title>Hello Phoenix!</title>

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/styles/default.min.css">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <!-- Navigation -->
    <%= render "navigation.html", conn: @conn %>
    <!-- End Navigation -->
    <!-- Content -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="container clearfix">
            <%= render "alerts.html", conn: @conn %>

            <%= render @view_module, @view_template, assigns %>
          </div>
        </div>
      </div>
    </div>
    <!-- End Content -->

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/highlight.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        hljs.initHighlightingOnLoad();
      });
      $(window).scroll(function() {
        if ($(document).scrollTop() > 50) {
          $('nav').addClass('shrink');
        } else {
          $('nav').removeClass('shrink');
        }
      });
    </script>
  </body>
</html>

web/templates/layout/navigation.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="/images/synarii.png" alt="Synarii"/>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="current"><a href="/">Home</a></li>
        <%= if current_user = @conn.assigns[:current_user] do %>
          <li><a href='/users/<%= current_user.id %>/posts'>Posts</a></li>
          <li><a href="/users">Users</a></li>
          <li>
            <%= link "Log out", to: session_path(@conn, :delete, current_user.id), method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>